In [27]:
from pytrends.request import TrendReq
import pandas as pd
import datetime as dt
from dateutil.relativedelta import relativedelta

In [28]:
pytrend = TrendReq(hl='en-US', tz=360)

In [29]:
# Import movie titles and release dates
movie_df = pd.read_csv("output/complete_movie_list_df.csv")
movie_df

,Unnamed: 0,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Poster,Metascore,imdbRating,BoxOffice,Production
0,0,Pirates of the Caribbean: Dead Man's Chest,2006,PG-13,07 Jul 2006,151 min,"Action, Adventure, Fantasy",Gore Verbinski,"Ted Elliott, Terry Rossio, Stuart Beattie","Johnny Depp, Orlando Bloom, Keira Knightley",Jack Sparrow races to recover the heart of Dav...,"English, Turkish, Greek, Mandarin, French",https://m.media-amazon.com/images/M/MV5BMTcwOD...,53.0,7.3,"$423,315,812",NaN
1,1,Night at the Museum,2006,PG,22 Dec 2006,108 min,"Adventure, Comedy, Family",Shawn Levy,"Robert Ben Garant, Thomas Lennon, Milan Trenc","Ben Stiller, Carla Gugino, Ricky Gervais",A newly recruited night security guard at the ...,"English, Italian, Hebrew",https://m.media-amazon.com/images/M/MV5BMTQyOT...,48.0,6.4,"$250,863,268","20th Century Fox, 21 Laps Entertainment, 1492 ..."
2,2,Cars,2006,G,09 Jun 2006,117 min,"Animation, Adventure, Comedy","John Lasseter, Joe Ranft","John Lasseter, Joe Ranft, Jorgen Klubien","Owen Wilson, Bonnie Hunt, Paul Newman",A hot-shot race-car named Lightning McQueen ge...,"English, Italian, Japanese, Yiddish",https://m.media-amazon.com/images/M/MV5BMTg5Nz...,73.0,7.1,"$244,082,982","Walt Disney Pictures, Pixar Animation Studios"
3,3,X-Men: The Last Stand,2006,PG-13,26 May 2006,104 min,"Action, Adventure, Sci-Fi",Brett Ratner,"Simon Kinberg, Zak Penn","Patrick Stewart, Hugh Jackman, Halle Berry",The human government develops a cure for mutat...,English,https://m.media-amazon.com/images/M/MV5BNDBhND...,58.0,6.7,"$234,362,462","Marvel Enterprises, Twentieth Century Fox"
4,4,The Da Vinci Code,2006,PG-13,19 May 2006,149 min,"Mystery, Thriller",Ron Howard,"Akiva Goldsman, Dan Brown","Tom Hanks, Audrey Tautou, Jean Reno","A murder inside the Louvre, and clues in Da Vi...","English, French, Latin, Spanish",https://m.media-amazon.com/images/M/MV5BMjIxMj...,46.0,6.6,"$217,536,138","Imagine Entertainment, Sony Pictures Entertain..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6893,6893,"Ma Belle, My Beauty",2021,NaN,20 Aug 2021,93 min,"Drama, Romance",Marion Hill,Marion Hill,"Idella Johnson, Hannah Pepper, Lucien Guignard",A surprise reunion in the South of France reig...,"English, French",https://m.media-amazon.com/images/M/MV5BMjU5Nj...,65.0,6.0,"$27,558",NaN
6894,6894,Jakob's Wife,2021,Not Rated,16 Apr 2021,98 min,Horror,Travis Stevens,"Mark Steensland, Kathy Charles, Travis Stevens","Barbara Crampton, Larry Fessenden, Bonnie Aarons","Anne, married to a small-town Minister, feels ...",English,https://m.media-amazon.com/images/M/MV5BYWQ5Nj...,59.0,5.5,"$26,114",NaN
6895,6895,Our Ladies,2019,R,18 Jun 2021,106 min,"Comedy, Drama",Michael Caton-Jones,"Michael Caton-Jones, Alan Sharp, Alan Warner","Abigail Lawrie, Rona Morison, Marli Siu","In 1990s Scotland, a group of Catholic school ...",English,https://m.media-amazon.com/images/M/MV5BMTgyMD...,NaN,6.9,"$25,386",NaN
6896,6896,The Night,2020,NaN,24 Feb 2021,105 min,"Horror, Mystery, Thriller",Kourosh Ahari,"Kourosh Ahari, Milad Jarmooz","Shahab Hosseini, Niousha Noor, Leah Oganyan",An Iranian couple living in the US become trap...,"Persian, English",https://m.media-amazon.com/images/M/MV5BN2M3NG...,68.0,5.5,NaN,NaN
6897,6897,John and the Hole,2021,R,06 Aug 2021,103 min,"Drama, Thriller",Pascual Sisto,Nicolás Giacobone,"Charlie Shotwell, Michael C. Hall, Jennifer Ehle",A coming-of-age psychological thriller that pl...,English,https://m.media-amazon.com/images/M/MV5BMDliZj...,62.0,5.3,NaN,NaN

In [88]:
# fix datetime conversion
problem_entries = []
for index, row in movie_df.iterrows():
    try:
        title = row["Title"].split(': ')[0] + " movie"
        release_date = dt.datetime.strptime(row["Released"], "%d %b %Y")
        start_date = release_date - relativedelta(years=1)
        release_date = release_date.strftime("%Y-%m-%d")
        start_date = start_date.strftime("%Y-%m-%d")
        timeframe = f'{start_date} {release_date}'  
    except TypeError:
        print("bad data", title)
        problem_entries.append(title)
        pass
    # print(title, start_date, release_date)
    pytrend.build_payload(kw_list=[title], timeframe=timeframe')
    df = pytrend.interest_over_time()
    try:
        buzz = len(df.loc[df[title] >= 20])
    except KeyError:
        problem_entries.append(title)
        pass
    movie_df.loc[index, "Buzz"] = buzz
    print(title)

Pirates of the Caribbean movie
Night at the Museum movie
Cars movie
X-Men movie
The Da Vinci Code movie
Superman Returns movie
Happy Feet movie
Ice Age movie
Casino Royale movie
The Pursuit of Happyness movie
Over the Hedge movie
Talladega Nights movie
Click movie
Mission movie
The Departed movie
Borat movie
The Devil Wears Prada movie
The Break-Up movie
Dreamgirls movie
Scary Movie 4 movie
Failure to Launch movie
Inside Man movie
Open Season movie
The Santa Clause 3 movie
Charlotte's Web movie
The Pink Panther movie
Eight Below movie
Saw III movie
Nacho Libre movie
You, Me and Dupree movie
Eragon movie
Monster House movie
Jackass Number Two movie
R.V. 2015 movie
V for Vendetta movie
World Trade Center movie
Rocky Balboa movie
Big Momma's House 2 movie
Step Up movie
Flushed Away movie

ResponseError: The request failed: Google returned a response with code 500.

In [90]:
len(problem_entries)

3

In [89]:
title = "Déjà Vu" + " movie"
release_date = "2017-11-17"
start_date_ojb = dt.datetime.strptime(release_date, '%Y-%m-%d') - relativedelta(years=1)
start_date = start_date_ojb.strftime('%Y-%m-%d')
timeframe = f'{start_date} {release_date}'
# print(timeframe)
pytrend.build_payload(kw_list=[title], timeframe=timeframe)
df = pytrend.interest_over_time()
len(df)
# buzz = len(df.loc[df[title] >= 20])
# movie_df.loc[index, "Buzz"] = buzz
# print(buzz)
# df

52

In [44]:
title = "mulan movie"
release_date = "2020-03-09"
start_date_ojb = dt.datetime.strptime(release_date, '%Y-%m-%d') - relativedelta(years=1)
start_date = start_date_ojb.strftime('%Y-%m-%d')
timeframe = f'{start_date} {release_date}'
print(timeframe)
pytrend.build_payload(kw_list=[title], timeframe=timeframe)
df = pytrend.interest_over_time()
buzz = len(df.loc[df[title] >= 20])
#movie_df.loc[index, "Buzz"] = buzz
print(buzz)
df

2019-03-09 2020-03-09
21

            mulan movie  isPartial
date
2019-03-10           15      False
2019-03-17           12      False
2019-03-24            9      False
2019-03-31           11      False
2019-04-07           15      False
2019-04-14           10      False
2019-04-21           10      False
2019-04-28            9      False
2019-05-05           10      False
2019-05-12           12      False
2019-05-19           18      False
2019-05-26           15      False
2019-06-02           16      False
2019-06-09           11      False
2019-06-16           19      False
2019-06-23           12      False
2019-06-30           19      False
2019-07-07          100      False
2019-07-14           39      False
2019-07-21           38      False
2019-07-28           20      False
2019-08-04           19      False
2019-08-11           21      False
2019-08-18           22      False
2019-08-25           17      False
2019-09-01           16      False
2019-09-08           16      False
2019-09-15           18      False
2019-09-22           17      False
2019-09-29           13      False
2019-10-06           17      False
2019-10-13           15      False
2019-10-20           15      False
2019-10-27           16      False
2019-11-03           12      False
2019-11-10           16      False
2019-11-17           16      False
2019-11-24           10      False
2019-12-01           35      False
2019-12-08           29      False
2019-12-15           23      False
2019-12-22           24      False
2019-12-29           24      False
2020-01-05           25      False
2020-01-12           23      False
2020-01-19           24      False
2020-01-26           26      False
2020-02-02           34      False
2020-02-09           28      False
2020-02-16           26      False
2020-02-23           40      False
2020-03-01           55      False
2020-03-08           79      False